name: Check
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: '3.3.9'
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze
